version: '3.8'

services:

  tf-serving:
    image: tensorflow/serving:latest
    container_name: tf_model
    ports:
      - "8501:8501"
    volumes:
      - ./model:/models/sentiment
    environment:
      - MODEL_NAME=sentiment
    networks:
      - sentiment_network

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - tf-serving
    networks:
      - sentiment_network
    environment:
      - TF_SERVING_HOST=tf-serving

networks:
  sentiment_network:
    driver: bridge